[phases.setup]
aptPkgs = [
  "php",
  "php-cli",
  "php-curl",
  "php-xml",
  "php-mbstring",
  "php-sqlite3",
  "php-intl",
  "git",
  "unzip",
  "curl"
]

cmds = [
  "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer",
  "php /usr/local/bin/composer install --no-dev --optimize-autoloader"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public public/index.php"

