[build]
builder = "nixpacks"

[deploy]
startCommand = "php -S 0.0.0.0:$PORT -t public public/index.php"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
RAILWAY_BUILDER = "nixpacks"
